name: Tests
on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - master
jobs:
  tests:
    strategy:
      matrix:
        node: [14.x, 15.x]
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install --prefer-offline --no-fund --no-progres
    - run: npm run lint
    - run: npm run test
